package com.ordersmanagement.DataAccessLayer;

import com.ordersmanagement.Model.Order;

import java.sql.*;

public class OrderDAO extends AbstractDAO<Order> {

    /**
     * Default constructor for OrderDAO.
     */
    public OrderDAO() {
        super();
    }

    /**
     * Inserts an order and returns the generated ID using the provided connection.
     * Assumes order_date is auto-generated by the database.
     *
     * @param order the Order object to insert
     * @param connection the active database connection
     * @return the generated order ID
     * @throws SQLException if insertion fails or no ID is obtained
     */
    public int insertOrder(Order order, Connection connection) throws SQLException {
        String sql = "INSERT INTO orders(client_id) VALUES(?)";

        try (PreparedStatement stmt = connection.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS)) {
            stmt.setInt(1, order.getClientId());
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                throw new SQLException("Creating order failed, no rows affected.");
            }
            try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    return generatedKeys.getInt(1);
                } else {
                    throw new SQLException("Creating order failed, no ID obtained.");
                }
            }
        }
    }
}
